// <auto-generated />
using Fitness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fitness.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20201103000804_CustomUserFields")]
    partial class CustomUserFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fitness.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<string>("Difficulty");

                    b.Property<string>("Name");

                    b.Property<string>("Target");

                    b.Property<string>("Type");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Calories = 20,
                            Difficulty = "Medium",
                            Name = "Pushups",
                            Target = "Arms",
                            Type = "Strength"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Calories = 20,
                            Difficulty = "Hard",
                            Name = "Sumo Squats",
                            Target = "Legs",
                            Type = "Strength"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Calories = 20,
                            Difficulty = "Easy",
                            Name = "Bicep Curls",
                            Target = "Arms",
                            Type = "Strength"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Calories = 20,
                            Difficulty = "Easy",
                            Name = "Situps",
                            Target = "Core",
                            Type = "Strength"
                        },
                        new
                        {
                            ExerciseId = 5,
                            Calories = 20,
                            Difficulty = "Hard",
                            Name = "Plank",
                            Target = "Core",
                            Type = "Strength"
                        },
                        new
                        {
                            ExerciseId = 6,
                            Calories = 20,
                            Difficulty = "Medium",
                            Name = "Squats",
                            Target = "Legs",
                            Type = "Strength"
                        },
                        new
                        {
                            ExerciseId = 7,
                            Calories = 20,
                            Difficulty = "Easy",
                            Name = "Tricep Kickbacks",
                            Target = "Arms",
                            Type = "Strength"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
