// <auto-generated />
using Fitness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fitness.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20201102183124_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fitness.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<string>("Difficulty");

                    b.Property<string>("Name");

                    b.Property<string>("Target");

                    b.Property<string>("Type");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
